services:
  mysql:
    image: mysql:8.4
    container_name: s7801-mysql
    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    ports:
      - "${MYSQL_PORT}:3306"

    volumes:
      - s7801_mysql_data:/var/lib/mysql

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mysqladmin ping -h 127.0.0.1 -uroot -p$$MYSQL_ROOT_PASSWORD"
        ]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 20s


volumes:
  s7801_mysql_data:
    name: s7801_mysql_data